default:
  data: "data"
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_interim: "data/interim"
  data_external: "data/external"
  plots: "reports/figures"
  model_dl: "models/DL"
  model_ml: "models/ML"